language: python
python:
- '2.7'
- '3.2'
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y python-pygame
install:
- pip install numpy
- pip install cx_Freeze
script:
- cxfreeze main.py
- cp -r dist/* ./
- rm -r dist/

